config/routes.rb
Rails.application.routes.draw do
  get 'works/index'
  root 'works#index'
  get 'works/delete/:id' => 'works#delete', as: "delete_work"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :inventories
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :category
  has_one :work, dependent: :destroy
  validates :size, numericality: {greater_than: 0}
  after_destroy :record_serial_number

  scope :filter_by_size, ->(query) { where(size: query)  }

  def record_serial_number
    text = "La pieza con serial #{serial_number} ha sido borrada"
    Record.create(description: text)
  end
end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :works, dependent: :destroy
  validates :name, presence: true
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :user
  belongs_to :inventory

  scope :last_5, -> { order(created_at: :desc).limit(5) }
  scope :without_item, -> { where(inventory_id: nil)  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def delete
    @work = Work.find(params[:id])
    @work.destroy
    redirect_to works_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prueba2Alex</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">  
  <%= yield %>
  </div>
</body>
</html>

app/views/works/index.html.erb
<h1>Works</h1>
<table class="table">
    <thead>
      <tr>
        <th>Description</th>
        <th>User Name</th>
        <th>Item</th>
        <th>Category</th>
        <th>Destroy</th>
      </tr>
    </thead>
    <tbody>
      <% @works.each do |work| %>
      <tr>
        <td><%= work.description %></td>
        <td><%= work.user.try(:name) %></td>
        <td><%= work.inventory.try(:description) %></td>
        <td><%= work.inventory.try(:category).try(:name) %></td>
        <td><a href="<%= delete_work_path(id: work.id) %>"> DESTROY </a></td>
      </tr>
      <% end%>
    </tbody>
  </table>